# GitLeaks Configuration
# This file tells GitLeaks what to ignore

[allowlist]
# Ignore test credentials in CI workflows and documentation files
paths = [
  '''.github/workflows/ci-cd.yml''',
  '''test_.*.py''',
  '''.*_test.py''',
  '''CLAUDE.md''',
  '''TEST_CHECKLIST.md''',
  '''cors-config.json''',
  '''terraform/README.md'''
]

# Allow fake/test keys and localhost URLs
regexes = [
  '''-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC9W8bA\n-----END PRIVATE KEY-----''',
  '''test-key-id''',
  '''test@test-project''',
  '''localhost:[0-9]+''',
  '''127\.0\.0\.1:[0-9]+''',
  '''https?://localhost:[0-9]+.*''',
  '''https?://127\.0\.0\.1:[0-9]+.*''',
  '''http://localhost:5001.*''',
  '''pvpocket\.xyz'''
]