runtime: python311
entrypoint: gunicorn -b :$PORT run:app

# Scalability and Performance Settings
automatic_scaling:
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6
  max_concurrent_requests: 50
  max_instances: 10
  min_instances: 1

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

handlers:
- url: /.*
  script: auto
  secure: always

env_variables:
  FLASK_ENV: 'production'
  GCP_PROJECT_ID: "pvpocket-dd286"
  FIREBASE_SECRET_NAME: "firebase-admin-sdk-json"
  
  # Scalability Configuration
  USE_FIRESTORE_CACHE: 'false'  # Set to 'true' to use Firestore as cache backend
  CACHE_TTL_HOURS: '24'         # Card collection cache TTL in hours
  USER_CACHE_TTL_MINUTES: '30'  # User data cache TTL in minutes
  MAX_DB_CONNECTIONS: '15'      # Maximum database connection pool size
  MONITORING_ENABLED: 'true'    # Enable performance monitoring